version: '2.3'

services:

  base:
    image: library/postgres:latest
    env_file:
      - .env

  db:
    extends:
      service: base
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data:/var/lib/postgresql/data
    ports:
    - "54321:5432"

  assignment:
    extends:
      service: base
    environment:
      PGPASSWORD: $POSTGRES_PASSWORD
    volumes:
      - ./run.sh:/run.sh
    entrypoint: "/bin/sh run.sh"

  accessing-the-database:
    extends:
      service: assignment
    links:
      - db
    environment:
      POSTGRES_DB: university
    volumes:
      - ./accessing-the-database/sql:/sql

  basic-sql-part-1:
    extends:
      service: assignment
    links:
      - db
    environment:
      POSTGRES_DB: university
    volumes:
      - ./basic-sql-part-1/sql:/sql

  basic-sql-part-2:
    extends:
      service: assignment
    links:
      - db
    environment:
      POSTGRES_DB: movies
    volumes:
      - ./basic-sql-part-2/sql:/sql

  intermediate-sql:
    extends:
      service: assignment
    links:
      - db
    environment:
      POSTGRES_DB: university
    volumes:
      - ./intermediate-sql/sql:/sql